config/routes.rb
Rails.application.routes.draw do
  root "games#index"

  resources :games
  get 'cards/:id', to: 'cards#show'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/card.rb
class Card < ApplicationRecord
	belongs_to :game

	# only support 4 cards for now
	enum symbol: [ :jack, :queen, :king, :ace ]
end

app/models/game.rb
class Game < ApplicationRecord
	has_many :cards
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/cards_controller.rb
class CardsController < ApplicationController
  def show
    @card = Card.find(params[:id])
    render @card, locals: { show_card: params[:show_card] }
  end
end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  def index

    # Only support 1 game for now.
    @game = Game.find_or_create_by(id: 1)
    if @game.cards.empty?
      0.upto(7) do |i|
        c = Card.new(symbol: (i % 4), game_id: @game.id)
        c.save!
      end
    end
  end

  def update
    game = Game.find(params['id'])

    if params[:start_over]
      game.cards.each do |card|
        card.face_up = false
        card.selected_in_turn = false
        card.save!
      end

      game.turn_active = false
      game.save!
      redirect_to root_path
      return
    end

    card = Card.find(params['card'])

    if game.turn_active
      found_match = false
      prev_card = game.cards.find_by(selected_in_turn: true)

      if prev_card.symbol == card.symbol
        prev_card.face_up = true
        card.face_up = true
        found_match = true
      end

      prev_card.selected_in_turn = false
      prev_card.save!
      card.save! if found_match

      game.turn_active = false
      game.save!

      if found_match
        render json: { card: { id: card.id }, wait_then_refresh: false }
      else
        render json: { 
                        card: { id: card.id },
                        prev_card: { id: prev_card.id },
                        wait_then_refresh: true 
                      }
      end
    else
      card.selected_in_turn = true
      card.save!

      game.turn_active = true
      game.save!

      render json: { card: { id: card.id } , wait_then_refresh: false }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cards_helper.rb
module CardsHelper
end

app/helpers/games_helper.rb
module GamesHelper
end

app/views/cards/_card.html.erb
<div id="card-view-<%= card.id %>">
	<% if show_card || card.face_up %>

		<div class="card">
	  	<div class="card-body">Card <%= card.symbol %></div>
		</div>

	<% else %>

		<div class="card">
	  	<div
	  		class="card-body">
	  		<button type="button" id="btn-flip-<%= card.id %>" class="btn btn-primary" data-id=<%= card.id %> >
	  			Click me!
	  		</button>
	  		to reveal card
	  	</div>
		</div>

	<% end %>
</div>

app/views/games/index.html.erb
<h1>Games#index</h1>
<p>Game: <%= @game.id %></p>

<%= button_to 'Start Over', game_path(@game, start_over: true), method: :put  %>

<br />

<!-- Currently only showing cards in sequential order, but would like to expand on that -->
<% @game.cards.each do |card| %>
	<%= render card, show_card: false %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MemoryGame</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>